### PR TITLE
Fixed inability to set classic editor globally inside Writing settings in certain themes

### PR DESCRIPTION
**Pull request by eligt**
The WordPress Settings APIs were being used slightly incorrectly.

`register_setting` needs to be called after `add_settings_field`, not before and also options names are supposed to use underscores and not hyphens as separators. 

These changes allow saving the settings for certain themes (or plugin combinations) that would otherwise be unable to save and would be stuck on Block editor.

### CODE REVIEW

**Comment by luciano-croce** [comment]
@eligt 

"certain themes"

Foe example?

**Comment by eligt** [comment]
For instance all TeslaThemes.com as well as ShowThemes.com (themes I help maintain) but there might be others.

**Comment by luciano-croce** [comment]
Thanks!

**Comment by eligt** [comment]
You're right, it didn't occur to me about the existing users (as we just introduced this plugin as a requirement). It seems like it was an error on our side, options name can indeed contain hyphens, using underscores is just the standard.

So, you can ignore the change of options names, but I do think `register_setting` should be called after `add_settings_field`, again based on the documentation, and this should definitely be a safe change.

**Comment by azaozz** [comment]
@eligt Updated the PR fo remove option names changes. Where is recommended to do `register_setting`  after `add_settings_field`? Logically it seems the other way around is better, first you "register" then you add fields to the registered setting (although it seems the order doesn't matter)? :)

Looking at https://developer.wordpress.org/plugins/settings/using-settings-api/ seems they are listed in that order too.

**Comment by eligt** [comment]
@azaozz Yup, that's where I was getting it from. The call order is not formally instructed anywhere in the documentation, but all examples use that order. I think as of right now it works both ways but given the official docs do it in that order it might be safer. Considering we fixed this issue on our side (which wasn't due to call order anyway) I'll leave it up to you if you want to make that change, if not you can just reject the PR and I won't be offended :)

**Comment by azaozz** [comment]
Yeah, the (only) example in the docs shows `register_setting()` before `add_settings_field()`. 

```php
function wporg_settings_init()
{
    // register a new setting for "reading" page
    register_setting('reading', 'wporg_setting_name');
 
    // register a new section in the "reading" page
    add_settings_section(
        'wporg_settings_section',
        'WPOrg Settings Section',
        'wporg_settings_section_cb',
        'reading'
    );
 
    // register a new field in the "wporg_settings_section" section, inside the "reading" page
    add_settings_field(
        'wporg_settings_field',
        'WPOrg Setting',
        'wporg_settings_field_cb',
        'reading',
        'wporg_settings_section'
    );
}
```

Thinking we are good here.

**Pull request closed without merging**
