### PR TITLE
block-editor-plugin.js -- deleting all blank lines to reduce the script size

### PR DESCRIPTION
**Pull request by luciano-croce**
- Deleting all blank lines to reduce the script size.

### CODE REVIEW

**Comment by azaozz** [comment]
The script is super small, and is not used yet. Maybe we can look again when it is enabled?

**Comment by luciano-croce** [comment]
"Maybe we can look again when it is enabled?"

Yes!

**Comment by luciano-croce** [comment]
Also consider the possibility of creating a minifiled file:

block-editor-plugin.js
block-editor-plugin.min.js

**Comment by luciano-croce** [comment]
Closed because I have add another PR more detailed for this issue.

**Pull request closed without merging**
