### PR TITLE
Add CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by luciano-croce**

### CODE REVIEW

**Comment by azaozz** [comment]
Hmm, do we really need this? We probably would, if we had lets say... 100-200 contributors, but for now..? :)

**Comment by chrisvanpatten** [comment]
Also if using a code of conduct it might be better to use the one in the Gutenberg repo, which references the existing WordPress community standards.

**Comment by luciano-croce** [comment]
OK also for me.

**Comment by ntwb** [comment]
Closing per the above

**Pull request closed without merging**
